# Generated by Django 2.0.7 on 2018-07-29 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DeckUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benkyo.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_cd', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='deckuser',
            name='role_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benkyo.Role'),
        ),
        migrations.AddField(
            model_name='deckuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deckuser',
            unique_together={('deck_id', 'user_id', 'role_cd')},
        ),
    ]
