# Generated by Django 2.0.7 on 2020-02-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benkyo', '0007_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_cd', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cardtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cardtag',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='private',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date_to_review',
        ),
        migrations.AddField(
            model_name='card',
            name='info',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='status_cd',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SEEN', 'SEEN'), ('FAMILIAR', 'FAMILIAR'), ('KNOWN', 'KNOWN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='setting',
            field=models.CharField(choices=[('TAGS', 'TAGS'), ('QUESTION_SIDE', 'QUESTION_SIDE'), ('SHUFFLE', 'SHUFFLE'), ('START_INDEX', 'START_INDEX'), ('END_INDEX', 'END_INDEX')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CardTag',
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='benkyo.Category'),
        ),
    ]
